# Generated by Django 4.2.2 on 2023-07-02 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tickets", "0003_alter_ticket_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="manager",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="managed_tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
