# Generated by Django 4.2.2 on 2023-07-05 11:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0004_alter_ticket_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
